### ISSUE TITLE
problem in application launch in chrome v 63 and 64

### ISSUE THREAD

**Issue by mib-kamel** [PolymerX/polymer-skeleton#100]
Hello

The polymer-skeleton app is working fine for me in firefox quantum.

But always get an error when I run the script "yarn dev:module" and try to open it in chrome v 63 or 64.

the error message is:

Uncaught TypeError: Cannot read property 'webpackHotUpdate' of undefined
    at window.JSCompiler_renameProperty (bootstrap eeee88485f55dfc4e65b:4)
    at module.bundle.js:728
window.JSCompiler_renameProperty @ bootstrap eeee88485f55dfc4e65b:4
(anonymous) @ module.bundle.js:728

**Comment by LasaleFamine** [comment]
Hi @mib-kamel, thanks for using the Skeleton :D 

This is actually a known problem of Webpack, you can check out the related issue to solve partially this problem right now: https://github.com/PolymerX/polymer-skeleton/issues/71. 
Let me know if you have other problems.

**Comment by mib-kamel** [comment]
Yes, it worked thank you

Now how can I make a build which works in both firefox and chrome?

**Comment by LasaleFamine** [comment]
The build command will create two bundles both for Firefox alike browsers and Chrome alike browsers. The splitted build is only for the dev command. I planned to add both builds also for the dev command asap.

**Comment by mib-kamel** [comment]
Worked.

Thank you :)
