### ISSUE TITLE
Ready for production ?

### ISSUE THREAD

**Issue by fuunnx** [PolymerX/polymer-skeleton#102]
First of all, thanks for this great skeleton, I love it.
Polymer 2 seems stuck into the past with bower and html imports. And it hurts to get back to it now that I have been using the latest features of CSS and javascript thanks to babel and postcss.

I'm starting a greenfield project right now and I'd like to know if this skeleton is ready for production ? I see that you are using Polymer 3 preview and it's hard to know 
1. compatibility regarding older browsers *with transpilation enabled* (Polymer 3 compatibility table is fuzzy and doesn't take transpiling into account)
2. You mention that you are not supporting IE11 and this is fine. However I need to include it in my project. What is missing that I should take care of ?
3. In your experience are Polymer 1+2 elements compatible with Polymer 3 ?

Have a good day

**Comment by equinusocio** [comment]
@LasaleFamine

**Comment by LasaleFamine** [comment]
Hey there! Thank you for your question.

Yeah, we are using Polymer 3 in preview, but you should know that Polymer 3 is nothing more than Polymer 2 but on NPM. APIs are the same and mostly everything I think will remain the same also for a 3.x stable release. You can check out the [Polymer blog's last article for more info about the future](https://www.polymer-project.org/blog/2017-11-27-future-of-elements.html).

About your points:

1. The skeleton uses Babel for transpilation to ES5, however the build is also configured to produce an ES6 version of the bundle (for new browsers). Using the `<script type="module">` we are able to load the correct version for the correct type of browser. I think this is a good solution to avoid useless transpilation.

2. Actually I think the Skeleton should be fine also for IE11 currently. Not supporting it means we will not solve any build-framework related bugs.

3. Polymer 2 elements (written with Classes syntax and not the legacy one) are the same of 3.x elements. Anyway if you also  wrote Polymer 1 elements in ES6, the upgrade should be smooth. 2.x elements should work out of the box and you just need a switch from HTML imports to ES6 imports. Guys at Polymer are working hard on the https://github.com/Polymer/polymer-modulizer, you should take a look also at this tool to upgrade your old elements.

If you want, check out [my article on Medium](https://codeburst.io/polymer-skeleton-webpack-postcss-service-workers-and-the-future-50189fbea23f) about the Skeleton, maybe you will find more answers!

I hope it helps!

**Comment by fuunnx** [comment]
Awesome thanks !

**Comment by fuunnx** [comment]
Just a follow up. I've been migrating successfully to Polymer 3 thanks to your skeleton 🎉 

However to keep on importing older elements managed by `bower` I had to make some changes into the webpack config and attach `Polymer` to the window object.

Thanks =)

**Comment by LasaleFamine** [comment]
Awesome, I'm glad it helps!
