### ISSUE TITLE
dev:module js error: app does not launch

### ISSUE THREAD

**Issue by arbrebinaire** [PolymerX/polymer-skeleton#103]
Hi,

The app does not load when using:

`yarn dev:module`

Here's the stack trace:

```
Uncaught TypeError: Cannot read property 'webpackHotUpdate' of undefined
    at window.JSCompiler_renameProperty (bootstrap 118089ef6b40cf5b491a:4)
    at module.bundle.js:728
window.JSCompiler_renameProperty @ bootstrap 118089ef6b40cf5b491a:4
(anonymous) @ module.bundle.js:728
```
Turns out "this" is undefined:

@ webpack:///webpack/bootstrap 5ef4e173adc67eac7fb1 line 4:

`var parentHotUpdateCallback = this["webpackHotUpdate"];`

This issue does not arise when launching the nomodule version.

Also: the https://github.com/PolymerX/skeleton-redux-example version does not have this issue in both module and nomodule versions.

Great work by the way.

**Comment by LasaleFamine** [comment]
Hi there, I'm sorry for the inconvenient, but this is actually a known bug of webpack. You can check the workaround here: https://github.com/PolymerX/polymer-skeleton/issues/71

**Comment by arbrebinaire** [comment]
Should have checked for a similar issue, sorry for the noise.  Thanks much for the workaround.
