### ISSUE TITLE
document.querySelector("any-component") not working

### ISSUE THREAD

**Issue by mib-kamel** [PolymerX/polymer-skeleton#106]
Hello all

I have a problem in using document.querySelector, document.getElementById or any other selection.

it always gives me null if I want to select anything.

**Comment by mib-kamel** [comment]
i should choose this.shadowRoot instead of document

**Comment by equinusocio** [comment]
Hi @mib-kamel, when you work with shadow dom you can't `querySelect` element outside the the eleme shadow root (and you should not do it). You can select elements inside the current node shadow-root by using, as you said, `this.shadowRoot`.

**Comment by mib-kamel** [comment]
thanks
