### ISSUE TITLE
Wrong feature check

### ISSUE THREAD

**Issue by Skeec** [PolymerX/polymer-skeleton#107]
In edge 41 the line 49 in file src/index.html
![image](https://user-images.githubusercontent.com/20649209/35292498-f6d61bc6-0070-11e8-9053-537763686c86.png)
There need to be extra parenthensis
`if (!'serviceWorker' in navigator) {` has to be `if (!('serviceWorker' in navigator)) {`

**Comment by LasaleFamine** [comment]
Wo, great catch @Skeec. This has to be fixed. Thank you so much for reporting this one.
