### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#11]
XO:
[![XO code style](https://img.shields.io/badge/code_style-XO-5ed9c7.svg?style=flat-square)](https://github.com/sindresorhus/xo)

PolymerX Skeleton (you can change the color and also the text):
[![Polymer Skeleton](https://img.shields.io/badge/polymerX-SKELETON-435877.svg?style=flat-square)](https://github.com/PolymerX/polymer-skeleton)

Github Release (or Tag?):
[![GitHub release](https://img.shields.io/github/release/PolymerX/polymer-skeleton.svg?style=flat-square)](https://github.com/PolymerX/polymer-skeleton)

Others? What do you think? @equinusocio

**Comment by equinusocio** [comment]
I like!
