### ISSUE TITLE
Update Polymer to 3.0-pre.4

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#111]
And we also need to switch from my fork of Polymer to a more generic PolymerX fork for removing the "flat" flag.

**Comment by equinusocio** [comment]
The pre.4 fix the npm issue?

**Comment by LasaleFamine** [comment]
I don't think so since the flag is specifically wanted for browser compatibility `import`, but I will try with clean Polymer `@next` install before re-forking it.
