### ISSUE TITLE
How to get it to work with meteor (no webpack available)

### ISSUE THREAD

**Issue by EliArtist** [PolymerX/polymer-skeleton#123]
I'm trying to create a project with meteor and polymer, was working quite well, but since polymer 3 I cant get it to work in the current Firefox version. First I thought it might be an error within Polymer 3 but then I found your project so I knew it had to work somehow but I could figure out how.
Could you explain roughly what you are doing while compiling? Like what files are you compiling at all and what steps are you doing with webpack that could be transferred to other compilers. Would be glad to help work this out :)

**Comment by yorrd** [comment]
Importing the `native-shim.js` from `custom-elements` works. I have no idea why, but it seems necessary to apply that transformation

**Comment by LasaleFamine** [comment]
Hey @EliArtist, thank you for your interest. Here is a little article about the features of the skeleton:  https://codeburst.io/polymer-skeleton-webpack-postcss-service-workers-and-the-future-50189fbea23f
