### ISSUE TITLE
$PORT not defined on Windows

### ISSUE THREAD

**Issue by DanielRuf** [PolymerX/polymer-skeleton#125]
On Windows `$PORT` is not set so the start script does not work by default.

**Comment by LasaleFamine** [comment]
Hi @DanielRuf,
actually the `"start"` script is used to deploy the Skeleton on Heroku. 

Of course you should change that script for your personal setup, but I would not consider this as a bug for the Skeleton.

Anyway, once the `polymerx-cli` will be completed, we won't have this kind of problem.

Sounds good?

**Comment by LasaleFamine** [comment]
I'm closing this one then.
