### ISSUE TITLE
problems with extended webpack config in dev script (svgsprite plugin)

### ISSUE THREAD

**Issue by DanielRuf** [PolymerX/polymer-skeleton#126]
I just get these errors

```
Uncaught (in promise) DOMException: Entry was not found.
properties-changed.js:122 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at SkApp.PropertiesChanged (properties-changed.js:122)
    at SkApp.PropertyAccessors (property-accessors.js:57)
    at SkApp.TemplateStamp (template-stamp.js:85)
    at SkApp.PropertyEffects (property-effects.js:1080)
    at SkApp.PropertiesMixin (properties-mixin.js:23)
    at SkApp.PolymerElement (element-mixin.js:335)
    at new SkApp (index.js:8)
    at Object.defineProperty.value (index.js:31)
    at __webpack_require__ (bootstrap 2043c26c27ce0f9f2593:19)
    at Object.defineProperty.value (index.js:6)
```

**Comment by LasaleFamine** [comment]
Hey @DanielRuf, can you please give us more details? 
Are you getting the error for both commands?
Are you checking the correct browsers when running the commands? (check out the readme for more details)
Did you make any changes or it is a fresh copy of the skeleton?

I can't help without this kind of details.
Thanks!

**Comment by DanielRuf** [comment]
I am using Chrome 60 on Windows.
Both scripts throw this error.

It was a fresh copy.

Fresh `dev` in incognito mode:
```
(index):90 GET http://localhost:3000/module.bundle.js net::ERR_ABORTED
componentsReady @ (index):90
(anonymous) @ webcomponents-loader.js:61
requestAnimationFrame (async)
fire @ webcomponents-loader.js:59
(anonymous) @ webcomponents-loader.js:66
(anonymous) @ webcomponents-loader.js:74
A bad HTTP response code (404) was received when fetching the script.
:3000/sw.js Failed to load resource: net::ERR_INVALID_RESPONSE
(index):71 Error during service worker registration: TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
```

Fresh `dev:module` works but throws
```
(index):71 Error during service worker registration: TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
```

But is also very fragile when adding other webpack plugins eg for svg spritesheets.

I am using Windows 10 with Node 8 and npm 5.

**Comment by DanielRuf** [comment]
The requirement of the service workers does not make it easier for local testing.

**Comment by DanielRuf** [comment]
Also see https://github.com/DanielRuf/polymer-skeleton-svgsprites

**Comment by LasaleFamine** [comment]
> I am using Chrome 60 on Windows.

For developing on Chrome you need to run `dev:module`. As you said it works, and service workers are not generated for development with the current configuration, so it's simply a "not found" error that you won't have with a production build.
Anyway you can easily fix this 404 generating the service worker also for development or with better check before trying to register the workers (eg. an initialization script bundled with Webpack where you can check for the `process.env.NODE_ENV` variable).

> But is also very fragile when adding other webpack plugins eg for svg spritesheets.

Do you have any specific error?

Anyway I would prefer a [PostCSS plugin](https://www.npmjs.com/package/postcss-svg) for working with SVG.

Maybe @equinusocio can help? 

@DanielRuf if you don't have any other problem for loading the app with the `dev` and `dev:module` command please rename the issue so we can focus on the sprite plugin problem.

**Comment by DanielRuf** [comment]
No, in the normal dev mode the site still shows `loading`.

**Comment by LasaleFamine** [comment]
For the "dev" command you should use a no-module browser like FireFox. Please check out the Readme for more details.

**Comment by DanielRuf** [comment]
Ok, then we just have the svgsprite issue left.

**Comment by LasaleFamine** [comment]
Hey @DanielRuf, did you find a solution to your problem? I have updated Webpack, maybe now you can double check if this is still a problem. I'm closing for now, feel free to reopen!

**Comment by DanielRuf** [comment]
Will try to check then.

We stopped evaluating Polymer further as it introduced more issues compared to our React solutions.
