### ISSUE TITLE
Add PolymerRedux

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#13]
[PolymerRedux](https://github.com/tur-nr/polymer-redux)

**Comment by rutgervd** [comment]
I would also love to see this!

**Comment by LasaleFamine** [comment]
Hi @rutgervd, actually I was thinking to avoid Redux as dependency for the Skeleton just because maybe someone wants to add MobX or another state manager. Do you think could be useful to add as standard for the Skeleton? 
Anyway I'm using Redux with this Skeleton with the help of https://github.com/tur-nr/polymer-redux. PolymerRedux actually is not ready for Polymer 3, [but our forked version it is](https://github.com/PolymerX/polymer-redux).

**Comment by rutgervd** [comment]
Ha, cool! Thanks very much for the reply.

**Comment by markortiz** [comment]
I would also loved to see this as well. I'm just new to Polymer and have some background in React and Redux. It would be very helpful if we could implement redux in another repo or as a default. :)

**Comment by LasaleFamine** [comment]
So I think I will go for another example repo on how to use the Skeleton with Redux. I hope this weekend.

**Comment by LasaleFamine** [comment]
Hey guys, I have just pushed the example repo with the Redux implementation: https://github.com/PolymerX/skeleton-redux-example

I will improve it with some docs.
Happy New year :D
