### ISSUE TITLE
"New version" popup

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#136]
We should show a "New version. Update" popup to update the Service Workers when a new version is released.

Something like this: https://github.com/webcomponents/webcomponents.org/blob/f7027235caece5b912aea04a6ea34ef05449ccc0/client/src/lazy-block.html#L96

**Comment by socceroos** [comment]
I'm interested in seeing how you'd push this from workbox on index.html through to the custom components.

**Comment by LasaleFamine** [comment]
I think this is a good starting point: https://github.com/PolymerX/polymer-skeleton/commit/8162b26324087527985ba657591cf425d660e4ce

We can made a custom element for this that includes the toast for alerting the user. @equinusocio what do you think?
