### ISSUE TITLE
Base template and base components

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#16]
Need to work on a base template like the Polymer Starter Kit (but better 😄 ).

We can also check:

- [polymer-news](https://github.com/Polymer/news) (latest case study published by Polymer team)
- [polymer-shop](https://github.com/Polymer/shop)

Of course I'm talkin about some basic configuration of the `index.html` and few more files, but of course we have a different structure and ***designers*** 💯

**Comment by equinusocio** [comment]
https://github.com/PolymerX/polymer-skeleton/tree/feature/demo-template

**Comment by LasaleFamine** [comment]
Yeeeees! These are the two main components, right? We can definitely give just this two (and maybe the `footer`) as identifiers of our **skeleton**, and just add the other two folder, `wrappers`  and `units` with two components as example.

What about include the `style-module` like: 

```html
...
<style include='style-module'></style>
...
```
For every components? Just to standardize.

What do you think?

**Comment by equinusocio** [comment]
Yes, the `style-module` import should be the same for every components. Maybe we should write some specifications/doc

**Comment by LasaleFamine** [comment]
Invalid. Ref #29
