### ISSUE TITLE
Branching for Polymer 2 - Webpack - PostCSS

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#17]
Yep, but maybe in a month or two.  Will be also the v2 of the Polymer Skeleton. 🚀

**Comment by LasaleFamine** [comment]
What about upgrading everything to Polymer 2 now as first thing?

**Comment by equinusocio** [comment]
I agree. There is no problems about the rc release? I mean breaking changes before the final release..

**Comment by LasaleFamine** [comment]
RC will not have breaking changes, but if will have some, I think will be small changes, so no problems!

We can close a bunch of issues before pushing the branch to the master.

**Comment by LasaleFamine** [comment]
So we need to switch from Webpack to Polymer-cli. Related #6.

Also we need to integrate the `polymer serve` with`postcss` and `browser-sync` (basically with our `dev` command).

Another thing could be to think about the folder structure as ferrety proposed with: 
   - `main-app.js`
   - `main-app.tpl.html`
   - `main-app.postcss`
   - `view.html` (or `main-app.html`)

**Comment by LasaleFamine** [comment]
I will be back on this and other issues this week end.

**Comment by LasaleFamine** [comment]
Proposal (just thinking):

 - `main-app.html`
 - `main-app.postcss`

During the development process the `.postcss` and the `.html` will be watched.
When `.postcss` is modified, the content is transpiled and is putted within the `.html`.

As we will not use `webpack` we can try to use the new [<script type="module">](https://developer.mozilla.org/en/docs/Web/HTML/Element/script#attr-type) instead.

**Comment by LasaleFamine** [comment]
New, definitive branch related: https://github.com/PolymerX/polymer-skeleton/tree/wp-polymer-2

**Comment by LasaleFamine** [comment]
Invalid. Refer #29 for Polymer 3.
