### ISSUE TITLE
Add postcss and remove node-sass

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#2]
Need to implement the [postcss-loader](https://github.com/postcss/postcss-loader) with `webpack` during development and also for the production build.

**Comment by equinusocio** [comment]
We also need this PostCSS plugin to incapsulate CSS:

- [Autoprefixer](https://github.com/postcss/autoprefixer#webpack)

We can also consider to add these plugins as a "starter kit":
- [CssNext](http://cssnext.io/usage/)
- [PostCSS Nested](https://github.com/postcss/postcss-nested)

**Comment by LasaleFamine** [comment]
Useful: [posthtml-postcss](https://github.com/posthtml/posthtml-postcss)

**Comment by equinusocio** [comment]
Yes!

**Comment by equinusocio** [comment]
https://github.com/posthtml/posthtml-loader

**Comment by LasaleFamine** [comment]
Give a try: [feature/postcss](https://github.com/PolymerX/polymer-webpack-skeleton/tree/feature/postcss)

      $ yarn dev:postcss

And start playing with the `webpack-app.usable.html` component. Could be a solution?
Currently only the `autoprefixer` plugin is loaded, but we can add other plugins easily.

**Comment by LasaleFamine** [comment]
Changed files, now we have:

  - `webpack-app.html` (main HTML with styles imported)
  - `webpack-app.style.html` (CSS file compiled with POSTCSS and included within the main HTML
  - `webpack-app.postcss.html` (PostCSS file that is watched during the `yarn dev:postcss`

Of course we need to avoid the `.style` file during development as we can load everything with Webpack. Need some changes to achieve this.

**Comment by equinusocio** [comment]
I can suggest a naming convention:
- `webpack-app.html`
- `style-module.html`
- `webpack-app.style.html` (without .postcss reference)

Since the `style-module.html` will be generated on build time, during development will we have only:
- `webpack-app.html`
- `webpack-app.style.html`

What do you think?

**Comment by LasaleFamine** [comment]
Looks great!

**Comment by LasaleFamine** [comment]
> Of course we need to avoid the .style file during development as we can load everything with Webpack. Need some changes to achieve this.

I think we simply can't.  
I tried some configurations with Wepback but there is no way to just load the compiled file in memory since we are obligated to `require` the CSS within the `es6.js` file and this is not good, because the best thing we can do is to encapsulate the CSS within the JS (and after within the body) and not the component itself.

What do you think if we maintain the four files with the names you proposed?
I pushed some changes, if you will run `yarn dev` it will watch both `.es6.js` and `.style.html` files and of course turn on a web server.  
`yarn dev:style` (the old `yarn dev:postcss`) and `yarn dev:js` (the old `yarn dev`) are still present.

We can think about further development in the future.

**Comment by equinusocio** [comment]
So we cant have this?

- `webpack-app.es6.js`
- `webpack-app.html` (main HTML with styles imported)
- `style-module.html` (CSS file compiled with POSTCSS and included within the main HTML)
- `style.postcss` (PostCSS file that is watched during the yarn dev:postcss without .postcss reference)

**Comment by LasaleFamine** [comment]
Oh yep, this could be a solution: compiling the `postcss` in inject it within the `style-module`. Will work on this ASAP.

**Comment by equinusocio** [comment]
better `webpack-app.postcss`
