### ISSUE TITLE
Rename starter-kit

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#3]
cc: @equinusocio

**Comment by equinusocio** [comment]
- Polymer Skeleton
- PolySkeleton
- Polymer S

**Comment by LasaleFamine** [comment]
Polymer Skeleton 👍 :1st_place_medal:

**Comment by LasaleFamine** [comment]
I will destroy every `ORIGIN`.   
***DON'T TRY THIS AT HOME*** 👊

**Comment by equinusocio** [comment]
- PolySalcazzo

**Comment by LasaleFamine** [comment]
Done
