### ISSUE TITLE
Make a beautiful logo

### ISSUE THREAD

**Issue by equinusocio** [PolymerX/polymer-skeleton#4]
This space is dedicated to discussions about the logo. This weekend i will work on this.

**Comment by equinusocio** [comment]
![logo](https://cloud.githubusercontent.com/assets/10454741/23586213/df302fc8-0190-11e7-8491-2fe56af661ef.jpg)

**Comment by LasaleFamine** [comment]
🎉 🎉 🎉 

I really like this, but give an eye on this: [start-polymer](https://github.com/StartPolymer). Of course they have the logo for the organization and not the project itself, so we can just use this because is a badass logo 🦄

**Comment by equinusocio** [comment]
@LasaleFamine 
<img width="996" alt="screen shot 2017-03-05 at 19 07 12" src="https://cloud.githubusercontent.com/assets/10454741/23589929/17657178-01d7-11e7-9496-dee2ac1b7f72.png">

![logo](https://cloud.githubusercontent.com/assets/10454741/23589948/576cc0d2-01d7-11e7-9bd6-f2deea96932f.jpg)

**Comment by equinusocio** [comment]
![logo2](https://cloud.githubusercontent.com/assets/10454741/23590392/47f1b57e-01df-11e7-9436-e6471104cc55.jpg)
