### ISSUE TITLE
Add basic PostCSS plugins 

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#45]

**Comment by equinusocio** [comment]
I think we don't have to provide plugins. Just the postcss core and loader and let people to add plugins they want.

**Comment by LasaleFamine** [comment]
The postcss config file must be present BTW. So, ok, but what if we want to build a sample template? No `autoprefixer` (for example) for `display: flex`? 😞

**Comment by equinusocio** [comment]
Autoprefixer is included in cssnext and css nano. A sample template should be simple with pure css, if we need autoprefixer for some rules we can use https://autoprefixer.github.io/

**Comment by LasaleFamine** [comment]
Alright then. An issue less 👍
