### ISSUE TITLE
Add build process

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#6]
`dist` folder? On `.gitignore`?

**Comment by equinusocio** [comment]
I like 'build' over dist

Il sab 4 mar 2017, 21:07 Alessio Occhipinti <notifications@github.com> ha
scritto:

**Comment by LasaleFamine** [comment]
Ok I will go for `build`

**Comment by equinusocio** [comment]
I like the idea to have a configuration file for the build process. This is the `polymer.json` configuration file for the `polymer-cli`, as example:

```json
{
  "entrypoint": "index.html",
  "shell": "src/shell-app.html",
  "fragments": [
    "src/dashboard-view.html",
    "src/status-view.html"
  ],
  "sources": [
    "src/**/*",
    "static/**/*",
    "bower.json"
  ],
  "extraDependencies": [
    "manifest.json",
    "bower_components/webcomponentsjs/webcomponents-lite.min.js",
    "bower_components/clab-ui-components/_assets/css/contactlab-pattern.css",
    "bower_components/clab-ui-components/_assets/fonts/**/*",
    "bower_components/ikonograph/dist/ikonograph.min.css",
    "bower_components/ikonograph/fonts/*"
  ]
}
```

**Comment by LasaleFamine** [comment]
I'm thinking about using the `polymer-cli` for our build. Polymer 2 is strictly related to the `polymer-cli` so I think we can go for it.

Anyway we need to rethink about the use of `webpack` 'cause the nature of Polymer 2. As we know the Polymer Slack is a mess right now. Just wait the next week, I think they will release another RC.
By the way could be a great opportunity to come back to the "origin" of the frontend development: less tools, more code 🗡 

Another awesome thing could be the customization of the `polymer-cli` itself.

**Comment by LasaleFamine** [comment]
We need to get rid of `webpack`. I'm thinking about some solution but the main could be remove `webpack` and start using the Polymer's tools withing PostCSS and [maybe a server-side-like rendering](https://github.com/Polymer/prpl-server-node).

**Comment by LasaleFamine** [comment]
Invalid. Refer #29
