### ISSUE TITLE
Dumbs folder seems non idiomatic

### ISSUE THREAD

**Issue by richardanaya** [PolymerX/polymer-skeleton#67]

**Comment by LasaleFamine** [comment]
Hi @richardanaya, can you please argument a bit your title? I think I'm not getting it 😅

**Comment by equinusocio** [comment]
Hi @richardanaya, we are take as references how other frameworks handle the components:
- https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0
> You’ll find your components much easier to reuse and reason about if you divide them into two categories. I call them Container and Presentational components* but I also heard Fat and Skinny, **Smart and Dumb**, Stateful and Pure, Screens and Components, etc. These all are not exactly the same, but the core idea is similar.

**Comment by LasaleFamine** [comment]
Hey @richardanaya, do you think we can close this one?

**Comment by richardanaya** [comment]
Go for it!
