### ISSUE TITLE
Hot reload breaks the application. Known bug of webpack.

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#71]
Running `yarn dev:module` for develop on browsers that supports `type=module` script import is causing an error due a known bug of webpack: https://github.com/webpack/webpack/issues/5776

Wait for a fix that should come soon, [I hope](https://github.com/webpack/webpack/pull/5862), we can now disable the hot reload during the development.

ERROR: `webpackHotUpdate`

**WORKAROUND**: remove the `--hot` flag from https://github.com/PolymerX/polymer-skeleton/blob/master/package.json#L15

**Comment by equinusocio** [comment]
Since webpack fixes this with this PR time ago...is this still valid? 
https://github.com/webpack/webpack/pull/5862

**Comment by LasaleFamine** [comment]
I should check before closing this one.

**Comment by LasaleFamine** [comment]
Solved with Webpack 4.
