### ISSUE TITLE
Add SVG/PNG to Workbox configuration.

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#76]
We should add SVG files on the glob path of Workbox: https://github.com/PolymerX/polymer-skeleton/blob/6cc16b84ea84f409ced40b151879d7dc1826052f/webpack.config.js#L66

```js
new WorkboxPlugin({
    globDirectory: outputPath,
    globPatterns: ['**/*.{html,js,css,svg,png}'],
    swDest: join(outputPath, 'sw.js')
 }),
```

**Comment by maxknee** [comment]
@LasaleFamine I would like to help out with this project. If possible can you assign to me?

**Comment by LasaleFamine** [comment]
Hi @maxknee, thank you for your interest. Just take this and open a PR, it's ok for me. Just don't forget to create the PR on the `develop` branch. Thank you!
