### ISSUE TITLE
"Add to home screen" alert

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#78]
We should add the logic for the "Add to home screen" alert.

- [x] Update app manifest
- [x] Update pwa assets

**Comment by equinusocio** [comment]
manifest validator:
https://manifest-validator.appspot.com/

**Comment by LasaleFamine** [comment]
[Uhm...](https://github.com/Polymer/pwa-starter-kit/blob/master/index.html#L33)
