### ISSUE TITLE
Cant Start Serve

### ISSUE THREAD

**Issue by dertuerke** [PolymerX/polymer-skeleton#79]
Hi, if i run

yarn dev

i get this error on chrome
![bildschirmfoto 2017-11-03 um 19 34 49](https://user-images.githubusercontent.com/2199151/32390299-26e7589e-c0ce-11e7-9ad7-e3a8ae4f6258.png)

**Comment by LasaleFamine** [comment]
Hey @dertuerke, you should run the yarn dev:module for working with Chrome and other browsers that support the script type module import.

**Comment by dertuerke** [comment]
Hi i tried both, but i become the same error :S

**Comment by LasaleFamine** [comment]
Uhm, this is strange. Are you on http://localhost:3000? Can you try to delete the Application Storage from the Application tab of the Chrome Dev Tools? So you can reload without caches or something. This is a strange behavior also for the first error message in your console.

**Comment by dertuerke** [comment]
@LasaleFamine here the error if i start with
`yarn dev:module`

![bildschirmfoto 2017-11-05 um 13 00 52](https://user-images.githubusercontent.com/2199151/32414526-7083f550-c229-11e7-99e1-3af11b3b90ef.png)

![bildschirmfoto 2017-11-05 um 13 01 49](https://user-images.githubusercontent.com/2199151/32414532-84607c38-c229-11e7-9080-d4589bdb0849.png)

**Comment by LasaleFamine** [comment]
Ok this is expected. This is related to #71. You should solve with the workaround. Let me know.

**Comment by dertuerke** [comment]
Ok thx :)

**Comment by LasaleFamine** [comment]
Hey @dertuerke, can we close this one?
