### ISSUE TITLE
Add linters configurations

### ISSUE THREAD

**Issue by equinusocio** [PolymerX/polymer-skeleton#8]
@LasaleFamine Do you think that we can add `eslint` and `stylelint` configuration files?

**Comment by LasaleFamine** [comment]
Currently we have [xo](https://github.com/sindresorhus/xo) as JS linter, I started the project with it.

I think is pretty good for Javascript files (maybe we can think also to [prettier](https://github.com/prettier/prettier), but will be a next step), but of course we can add [stylelint(?)](https://stylelint.io/).

**Comment by equinusocio** [comment]
I will add stylelint. Xo have a configuration file?

Il dom 5 mar 2017, 11:22 Alessio Occhipinti <notifications@github.com> ha
scritto:

**Comment by equinusocio** [comment]
#5

**Comment by LasaleFamine** [comment]
Anyway `xo` config is inside the `package.json`, if you need it in the future 😄
