### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dertuerke** [PolymerX/polymer-skeleton#84]
@LasaleFamine can u say me, why i dont see my changes in Develop if i pull?

Sorry for the issue, but i dont know how i can contact you :D

![image](https://user-images.githubusercontent.com/2199151/32428798-fa5f0bfe-c2c7-11e7-9e21-dab3ce0e573b.png)

**Comment by LasaleFamine** [comment]
Are you sure you are pulling from the main repo and not from your forked skeleton?
Anyway if you are in the Polymer Slack channel you can reach me there also. No problem for the issue anyway!
