### ISSUE TITLE
Edge is loading also the "nomodule" version of the bundle. Known missing feature.

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#87]
We should find a better check for Edge for loading the correct bundle (module or no module bundle) because it's currently impossible using the `nomodule` property for the script. More info: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10525830/

**Comment by mgibas** [comment]
Isn't that already implemented (as per link above) ?

**Comment by LasaleFamine** [comment]
Yep. I just need to test before closing this one.

**Comment by LasaleFamine** [comment]
As per:

Edge 38.14393.2068.0
EdgeHTML 14.14393

We are still having the issue as you can see from the snapshot below. I think we need to wait before closing this one.

![Edge is loading both bundles](https://image.ibb.co/f0Mbun/edge_module_nomodule.png "Edge is loading both bundles")

**Comment by mgibas** [comment]
I was looking into it lately and there is pending bug in edge that cause to download nomodule but it will not execute it

**Comment by LasaleFamine** [comment]
Yep, it is mentioned in the first comment of the issue
