### ISSUE TITLE
Link "preload": how to?

### ISSUE THREAD

**Issue by LasaleFamine** [PolymerX/polymer-skeleton#88]
Using `<link rel="preload" href="bundle.js" as="script">` could be useful for preloading the bundle, but we need to handle this for `module.bundle.js` and `bundle.js` to avoid the loading of useless bundle.

https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by dertuerke** [comment]
dont forget to include the fallback for "preload".
And i dont understand your question :S

**Comment by LasaleFamine** [comment]
It's more like a reminder. I don't want both bundle preloaded, but only the one is needed for the user's browser. I need to investigate if we can discern the type of browser using the link preload tag. Do you have some hints?

**Comment by dertuerke** [comment]
You can use the Preload-Tag without a Browser detection. 
It's the same as CSS. If the Browser can use the tag, they ignore it. You only need this to tags
`
<link rel="preload" href="bundle.js" as="script">
<script src="bundle.js"></scrip>
`
