### ISSUE TITLE
Consider both components and wrappers directories.

### ISSUE THREAD

**Issue by equinusocio** [PolymerX/polymer-skeleton#9]
@LasaleFamine Maybe we can consider to provide another directory beside the `components` one:

- Components (For modular components)
- Wrappers (for containers components like views, pages, components-containers)

What do you think?

**Comment by LasaleFamine** [comment]
Maybe the `wrappers` folder inside the `components` folder?

Like: 

       /src/components/
           |-- app -> files
           |-- wrappers -> component-folder -> files
           |-- units -> component-folder -> files

Is useful for every automated task having all the components within a single directory. Make sense?  

We need to think also a `mixins` or `behaviors` folder, may be outside the component directory, which contains all the `js` classes shared between every component (one could be Redux).
Maybe I will open another issue for this.

**Comment by equinusocio** [comment]
Oks 👍

**Comment by LasaleFamine** [comment]
Thinking about the tree structure, actually we can have another directory beside the `components` or maybe inside, but we can just assume this as ***good practice*** for the skeleton.  
We can think about a `layout` folder where place three (or more) components:

      /src/components/
           |-- wrappers -> component-folder -> files
           |-- units -> component-folder -> files
           ...
      /src/layout/
            |-- app -> files
            |-- header -> files
            |-- footer -> files

I don't know if it's too ***dogmatic***, but could be a good ***sharing point*** for using the skeleton.

Ideas?

**Comment by equinusocio** [comment]
Or this structure?

```
  /src/components/
       |-- wrappers (complex composed components like areas inside views)
           ├ component-folder -> files

       |-- units (units components)
           ├ component-folder -> files
     
       |-- /shell/  (views and shell elements)
           ├ app -> files
           ├ header -> files
           ├ footer -> files
```

or do you this is a bit complicated @LasaleFamine ?

**Comment by LasaleFamine** [comment]
I think mine it's more complicated :man_astronaut: 

+1 for your. Let's keep this open, I think also in relation to #16.

**Comment by equinusocio** [comment]
I think that `logically` both `shell`, `units` and `wrappers` are components and should stay inside the `component` folder. Otherwise the division should be made outside the component folder, and i don't like that.

**Comment by equinusocio** [comment]
@LasaleFamine This structure actually work?
