### ISSUE TITLE
BROWSERS variable not working on Windows

### ISSUE THREAD

**Issue by yshterev** [PolymerX/polymer-skeleton#93]
Running npm tasks on windows returns `'BROWSERS' is not recognized as an internal or external command`. A good universal solution is [this one](https://webpack.js.org/guides/environment-variables/).

`module.exports` in `webpack.config.js` needs to return a function. It should be a minor change in webpack setup and npm scripts.

**Comment by LasaleFamine** [comment]
Hi @yshterev. Thanks for catching this one. I should find a better way to pass that variables to the script, I knew it could lead to some problems. I will check your solution asap.

**Comment by LasaleFamine** [comment]
I think this is a pretty neat solution. Thank you for sharing this piece of Webpack's lost documentation 🙏 

Can you please test the `develop` branch on Windows and check is working as expected? @yshterev

**Comment by yshterev** [comment]
@LasaleFamine It works. `build` runs fine. In `dev:module` I get an error for missing `sw.js`. Am I missing something?

**Comment by LasaleFamine** [comment]
That error is expected since currently we are not building Service Workers during development. It is an addition I want on the skeleton, but I also want a smooth workflow with Webpack and Workbox, so I'm still thinking about it!

Thank you for your test. I will close this once merged on `master`.

**Comment by yshterev** [comment]
@LasaleFamine I found something that does not work. In `build:prod` task `NODE_ENV` is defined [here](https://github.com/PolymerX/polymer-skeleton/blob/develop/package.json#L14), but in webpack it is assigned as [process.env](https://github.com/PolymerX/polymer-skeleton/blob/develop/webpack.config.js#L14).

It is a similar problem with windows and actually both variables, `ENV` and `IS_DEV` are undefined, so when i run build:prod webpack does not enter production mode for plugins.

I think ENV, IS_DEV and OUTPUT should be defined in the [module.export function](https://github.com/PolymerX/polymer-skeleton/blob/develop/webpack.config.js#L117) and make `processEnv`, `copyStatic` and `plugins` functions similar to [shared](https://github.com/PolymerX/polymer-skeleton/blob/develop/webpack.config.js#L81), so they have access to the env variables.

I guess the same think will work for [webpack.module.config.js](https://github.com/PolymerX/polymer-skeleton/blob/develop/webpack-module.config.js#L7).

**Comment by yshterev** [comment]
IS_DEV and OUTPUT are working properly... ENV is always `undefined`

**Comment by LasaleFamine** [comment]
You are pretty right! This should be fixed like the first one. Thank you again 👍

**Comment by yshterev** [comment]
This works:
`const ENV = process.argv.find(arg => arg.includes('--env.NODE_ENV=production')) ? 'production' : 'development';` and then IS_DEV can be set based on ENV instead of checking for `webpack-dev-server`

I think it is better.

**Comment by LasaleFamine** [comment]
We can also just check for `NODE_ENV=production` with the `includes`, it makes sense if someone wants to pass the env variable within a Unix machine changing the default the script we propose. What do you think?

**Comment by yshterev** [comment]
Instead of using `--env.` - yes I guess it will also be more consistent.

**Comment by LasaleFamine** [comment]
You can still use the `webpack` syntax for that, the `includes` will catch also that. So I think both solutions should work.

**Comment by LasaleFamine** [comment]
Actually, the check on the `webpack-dev-server` is needed since we are using also the `CopyWebpackPlugin` and this should be run only when `webpack` is running, not with the dev server. 

I think we should check the `ENV` as we said, but the `IS_DEV` variable should be set based on the `webpack-dev-server`.

**Comment by LasaleFamine** [comment]
I think now we should be ok with this. I have merged the changes on `development`. Let me know if you encounter new problems.

**Comment by yshterev** [comment]
Looks good. Can we fix the service worker? In-memory issues [seem to be fixed](https://github.com/GoogleChrome/workbox/pull/808).. and setup looks ok. Why is it not working on dev?
