### ISSUE TITLE
CSS Optimizations

### ISSUE THREAD

**Issue by yshterev** [PolymerX/polymer-skeleton#94]
Some suggestions to make CSS build better:

- [x] Change `.postcss` extensions to `.pcss`. It has been [recommended](https://twitter.com/postcss/status/661645290622083073) by PostCSS dev team and already there are [plugins](https://plugins.jetbrains.com/plugin/8578-postcss-support) for its syntax.

- [x] Add `cssnano` - Keep in mind that both, cssnext and cssnano have build-in autoprefixer. Autoprefixer of cssnano should be disabled, while cssnext autoprefixer should enabled according to [this issue](https://github.com/MoOx/postcss-cssnext/issues/323).
- [ ] Add `postcss-import` plugin to work with cssnext. Global PostCSS file should be more organized by importing whatever is required in one file, instead of loading multiple global PostCSS files in js. Also global is good place to import `CSS` files from npm packages. Direct import of css inside postcss file works. Check out [this guide](https://blog.envylabs.com/webpack-2-postcss-cssnext-fdcd2fd7d0bd).

**Comment by equinusocio** [comment]
I think we can consider to remove cssnext and use separated plug-ins.

**Comment by yshterev** [comment]
I think cssnext is good. CSS variables already work on modern browsers (excluding IE11), but cssnext adds more features like nesting, mixins by allowing us to use (according to them) latest CSS syntax today. If this is correct cssnext syntax should become part of CSS standards in future. It makes a strong point for long-term use to me. 

@equinusocio What would you replace it with?

**Comment by equinusocio** [comment]
@yshterev CSSNext is just a wrapper of single postcss plugins. It use postcss plugins under the hood that can be used directly. If you check the [cssnext features page](http://cssnext.io/features/) you can see that each feature have his related postcss plugin. 

By using the plugins directly we will have more control over releases and, for example, we can use [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables) over [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) (used by cssnext) because the first one follow the spec and allow custom properties declaration inside any selector.

**Comment by yshterev** [comment]
@equinusocio Good :) I agree. I thought cssnext plugins were future-proof :(

**Comment by equinusocio** [comment]
> Change .postcss extensions to .pcss. It has been recommended by PostCSS dev team and already there are plugins for its syntax.
- [x] Done

**Comment by equinusocio** [comment]
> Add postcss-import plugin to work with cssnext. Global PostCSS file should be more organized by importing whatever is required in one file, instead of loading multiple global PostCSS files in js. Also global is good place to import CSS files from npm packages. Direct import of css inside postcss file works. Check out this guide.

@yshterev I'm not sure if i understood what do you mean. Are you talking about moving css dependencies inside the .pcss file? We are switching to `[postcss-easy-import](https://github.com/TrySound/postcss-easy-import)` so we can import styles from the local folder, from the root path and from node_modules.

**Comment by yshterev** [comment]
@equinusocio Sorry... I read it now and I agree what I wrote is confusing :confused:. I pretty much meant what you actually did. I called it **global** css because the folder holding the files is called `global-style`, but its not really global because it is scoped to the `sk-app` component.

**Comment by equinusocio** [comment]
`global-style` contains global reusable css like basic elements styling and animations. These files should be included in each component style, when needed. In our demo template, we need those files only inside `sk-app`. But they can actually be imported inside each scoped component.

**Comment by yshterev** [comment]
I understand what you are trying ti achieve and it is not bad, but I think there is a pitfall.
All styles are compiled into the js bundle for each component individually. If you have a complex app and you import same CSS into many components the way you suggest, each component will have a copy of the same CSS in the bundle. This will result in a significantly bigger bundle size and also violates the DRY principle.

Polymer 1 had [shared-styles](https://www.polymer-project.org/1.0/docs/devguide/styling#style-modules) to solve that. I can't find anything similar for Polymer 3 - no more HTML imports.

By real global CSS I mean CSS that stays at document level, like [this](https://github.com/PolymerX/polymer-skeleton/blob/master/src/index.html#L19). It can be used to overwrite variables for themes and layouts for the entire application.

Regarding **cssnano** - It can be used for production builds only by [passing options to config](https://github.com/postcss/postcss-loader#context-ctx).

What do you think @LasaleFamine ?

**Comment by equinusocio** [comment]
@yshterev With Polymer 3 the `<style>` attribute is automatically used as "shared style". I agree with you but with Shadow DOM (not polymer) there is no way to avoid this and violate the DRY principle. You will have same CSS inside each component, but this follow the component dependencies management. So, if a component (or a set of components) doesn't need a specific keyframes, the css should not exist globally inside the document, but it should live inside the component. I can't find out a perfect solution, for now having a single source of global style is the best solution i found.

Maybe importing css files inside js can solve this problem? IDK

**Comment by yshterev** [comment]
It is ok for now I guess. There is an [open issue](https://github.com/Polymer/polymer/issues/4940) for API implementation.

**Comment by LasaleFamine** [comment]
I think currently there isn't a perfect solution for this problem. I think for sure the issue linked by @yshterev must be watched, also I think maybe we can achieve something similar to that `registerStyleModule` with the help of Webpack. I need to investigate more about this.

Anyway in a world of components, the shared CSS should be really small or maybe not present at all.

**Comment by LasaleFamine** [comment]
Well I think this is more a question about the standards of using the <link> tag inside the body. 
There are a bunch of answers about this question  (like https://webmasters.stackexchange.com/a/55133).

Talking about how this could affect the skeleton, in this case, I think the CSS won't be processed by the postcss-loader, but of course you can process your CSS as you want and load it with the link tag if you prefer.

**Comment by equinusocio** [comment]
@stagfoo You are talking linking the css inside an element or inside the document root (index.html)?
