### ISSUE TITLE
JS Spread syntax support

### ISSUE THREAD

**Issue by yshterev** [PolymerX/polymer-skeleton#99]
Currently using object spread like `const card = { ...model.item };` gives a compilation error. 

`babel-preset-env` does not support it by default so `babel-plugin-transform-object-rest-spread` plugin is needed as discussed [here](https://github.com/babel/babel-preset-env/issues/49).

I tested it on `webpack-module.config.js` - just added ` plugins: [["transform-object-rest-spread", {"useBuiltIns": true}]],` to babel-loader options and it seems to work.

**Comment by LasaleFamine** [comment]
Actually this is wanted. As you can see I proposed the `babel-preset-env` as feature, but not the spread plugin (which actually I add on every new project as first thing by the way). 

We can think to add also this as standard feature, but this is not a bug (@equinusocio 😋 ), could be a feature. 

Let's standardize this one.
